version: 2

models:
  - name: mart_product_performance
    description: "Product performance analytics with sales metrics and rankings"
    tests:
      - dbt_utils.expression_is_true:
          expression: "total_products >= 0"
    columns:
      - name: product_key
        description: "Surrogate key for product dimension"
        tests:
          - unique
          - not_null
