version: 2

models:
  - name: dim_category
    description: "Category dimension with sales performance metrics and hierarchical grouping"
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 50
          max_value: 200
      - dbt_expectations.expect_table_columns_to_match_ordered_list:
          column_list: ['product_category_name', 'product_category_name_english', 'category_display_name',
                        'total_products', 'total_orders', 'total_items_sold', 'total_revenue',
                        'avg_item_price', 'revenue_tier', 'category_size_tier', 'price_tier', 'category_group']
    columns:
      - name: product_category_name
        description: "Primary key - category name in Portuguese"
        tests:
          - not_null
          - unique

      - name: product_category_name_english
        description: "Category name translated to English"
        tests:
          - not_null

      - name: category_display_name
        description: "Title-cased English display name"

      - name: total_products
        description: "Count of unique products in this category"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_orders
        description: "Count of orders containing this category"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_items_sold
        description: "Total line items sold"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_revenue
        description: "Total revenue generated by this category"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: avg_item_price
        description: "Average price per item"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: revenue_tier
        description: "Category performance tier"
        tests:
          - accepted_values:
              values: ['Top Category', 'High Revenue', 'Medium Revenue', 'Low Revenue', 'Minimal Revenue', 'No Sales']

      - name: category_size_tier
        description: "Category size based on items sold"
        tests:
          - accepted_values:
              values: ['Large Category', 'Medium Category', 'Small Category', 'Niche Category', 'No Sales']

      - name: price_tier
        description: "Price range category"
        tests:
          - accepted_values:
              values: ['Premium', 'High', 'Medium', 'Low', 'Budget', 'Unknown']

      - name: category_group
        description: "High-level category grouping"
        tests:
          - accepted_values:
              values: ['Home & Furniture', 'Health & Beauty', 'Sports & Leisure', 'Electronics & Computers',
                       'Fashion & Accessories', 'Automotive', 'Books & Media', 'Arts & Gifts', 'Food & Pets',
                       'Office & Tools', 'Other']

  - name: dim_date
    description: "Date dimension with calendar attributes, fiscal periods, and Brazilian holidays"
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1000
          max_value: 2000
      - dbt_utils.expression_is_true:
          expression: "date_key = CAST(REPLACE(CAST(date_day AS VARCHAR), '-', '') AS INTEGER)"
          name: dim_date_key_format_validation
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD integer format"
        tests:
          - not_null
          - unique

      - name: date_day
        description: "Full date value"
        tests:
          - not_null
          - unique

      - name: year
        description: "Year extracted from date"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2016
              max_value: 2019
              inclusive: true

      - name: quarter
        description: "Quarter number (1-4)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 4
              inclusive: true

      - name: month_number
        description: "Month number (1-12)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
              inclusive: true

      - name: month_name
        description: "Full month name"
        tests:
          - not_null

      - name: week_of_year
        description: "Week number of year"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 53
              inclusive: true

      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 6
              inclusive: true

      - name: day_name
        description: "Full day name"
        tests:
          - not_null

      - name: is_weekend
        description: "Boolean flag for weekend days"
        tests:
          - not_null

      - name: is_weekday
        description: "Boolean flag for weekdays"
        tests:
          - not_null

      - name: is_holiday
        description: "Boolean flag for Brazilian holidays"
        tests:
          - not_null

  - name: dim_geography
    description: "Geography dimension with customer/seller locations and Brazilian regional data"
    columns:
      - name: zip_code_prefix
        description: "Primary key - first 5 digits of zip code"
        tests:
          - not_null
          - unique

      - name: city
        description: "City name"
        tests:
          - not_null

      - name: state
        description: "State name or abbreviation"
        tests:
          - not_null

      - name: state_clean
        description: "Standardized state abbreviation"
        tests:
          - not_null

      - name: latitude
        description: "Geographic latitude"
        tests:
          - dbt_utils.accepted_range:
              min_value: -34
              max_value: 6
              inclusive: true
              where: "latitude IS NOT NULL"

      - name: longitude
        description: "Geographic longitude"
        tests:
          - dbt_utils.accepted_range:
              min_value: -74
              max_value: -34
              inclusive: true
              where: "longitude IS NOT NULL"

      - name: customer_count
        description: "Number of customers at this location"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: seller_count
        description: "Number of sellers at this location"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_entities
        description: "Total customers + sellers"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: location_type
        description: "Type of location (Both/Customer Only/Seller Only)"
        tests:
          - accepted_values:
              values: ['Both', 'Customer Only', 'Seller Only', 'Unknown']

      - name: region
        description: "Brazilian region"
        tests:
          - accepted_values:
              values: ['North', 'Northeast', 'Central-West', 'Southeast', 'South', 'Unknown']

      - name: city_size_tier
        description: "City size category"
        tests:
          - accepted_values:
              values: ['Major City', 'Large City', 'Medium City', 'Small City', 'Rural']

  - name: dim_products
    description: "Product dimension with category information and sales performance metrics"
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 10000
          max_value: 50000
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: ['product_id']
    columns:
      - name: product_id
        description: "Primary key - unique product identifier"
        tests:
          - not_null
          - unique

      - name: product_category_name
        description: "Category name in Portuguese"

      - name: product_category_name_english
        description: "Category name in English"

      - name: product_weight_g
        description: "Product weight in grams"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              where: "product_weight_g IS NOT NULL"

      - name: product_volume_cm3
        description: "Calculated product volume"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              where: "product_volume_cm3 IS NOT NULL"

      - name: product_completeness_score
        description: "Data quality score (0-5)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
              inclusive: true

      - name: product_quality_tier
        description: "Product data quality tier"
        tests:
          - accepted_values:
              values: ['Excellent', 'Good', 'Fair', 'Poor']

      - name: product_size_category
        description: "Size category based on volume"
        tests:
          - accepted_values:
              values: ['Extra Small', 'Small', 'Medium', 'Large', 'Extra Large', 'Unknown']

      - name: product_weight_category
        description: "Weight category"
        tests:
          - accepted_values:
              values: ['Light', 'Medium', 'Heavy', 'Extra Heavy', 'Unknown']

      - name: total_revenue
        description: "Total revenue from this product"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: product_performance_tier
        description: "Sales performance tier"
        tests:
          - accepted_values:
              values: ['Top Seller', 'High Seller', 'Medium Seller', 'Low Seller', 'No Sales']

  - name: dim_sellers
    description: "Seller dimension with performance metrics and location information"
    columns:
      - name: seller_id
        description: "Primary key - unique seller identifier"
        tests:
          - not_null
          - unique

      - name: seller_zip_code_prefix
        description: "Seller location zip code prefix"
        tests:
          - not_null

      - name: seller_city
        description: "Seller city"
        tests:
          - not_null

      - name: seller_state
        description: "Seller state"
        tests:
          - not_null

      - name: seller_state_clean
        description: "Standardized state abbreviation"
        tests:
          - not_null

      - name: total_orders
        description: "Total orders fulfilled by seller"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_items_sold
        description: "Total items sold"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_revenue
        description: "Total revenue generated"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: avg_review_score
        description: "Average review score received"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true
              where: "avg_review_score IS NOT NULL"

      - name: positive_review_rate
        description: "Percentage of positive reviews"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true
              where: "positive_review_rate IS NOT NULL"

      - name: on_time_delivery_rate
        description: "Percentage of on-time deliveries"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true
              where: "on_time_delivery_rate IS NOT NULL"

      - name: seller_performance_tier
        description: "Overall performance tier"
        tests:
          - accepted_values:
              values: ['Top Performer', 'High Performer', 'Medium Performer', 'Low Performer', 'No Sales']

      - name: seller_size_tier
        description: "Seller size category"
        tests:
          - accepted_values:
              values: ['Large Seller', 'Medium Seller', 'Small Seller', 'Micro Seller', 'No Sales']

  - name: dim_customers
    description: "Customer dimension with location information and purchase behavior metrics"
    columns:
      - name: customer_key
        description: "Primary key - surrogate key for customer dimension"
        tests:
          - not_null
          - unique

      - name: customer_id
        description: "Natural key - unique customer identifier"
        tests:
          - not_null
          - unique
