version: 2

models:
  - name: mart_customer_analytics
    description: Customer analytics mart with aggregated metrics and segmentation
    tests:
      - dbt_utils.expression_is_true:
          expression: "total_customers >= 0"
    columns:
      - name: customer_key
        description: Surrogate key for customer dimension
        tests:
          - unique
          - not_null
