version: 2

models:
  - name: mart_seller_scorecard
    description: "Seller performance scorecard with ratings and sales metrics"
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 2000
          max_value: 10000
    columns:
      - name: seller_key
        description: "Surrogate key for seller dimension"
        tests:
          - unique
          - not_null
